### ISSUE TITLE
No Access for the Notebook

### ISSUE THREAD

**Issue by emilypi** [ocharles/effect-zoo#1]
Hey, the link on the front page to the notebook fails to grant access to arbitrary viewership, just a head's up. [This one](https://www.notion.so/09a6d3c82d24429ebe1fc99bc393bc7f) to be precise.

**Comment by ocharles** [comment]
I've made it public - can you see it now?

**Comment by ocharles** [comment]
It's not finished, so I should probably just remove the reference!

**Comment by emilypi** [comment]
Yes, thank you - it works.

**Comment by ocharles** [comment]
Cool, thanks for noticing!
